#!/usr/bin/env tcsh

##################################
# L2_setup 			 #
# Last Modified Date:   14/10/14 #
##################################

############################
# User defined environment #
############################

setenv L2_BASE_DIR "/home/rmb/devel/SPRAT/sprat_l2_pipeline"					# rmb/desktop
#setenv L2_BASE_DIR "/home/rmb/sprat_l2_pipeline"						# rmb/laptop

setenv L2_SUCCESS_LOG_PATH "/home/rmb/devel/SPRAT/sprat_l2_pipeline/logs/L2_success.log"	# rmb/desktop
#setenv L2_SUCCESS_LOG_PATH "/home/data/rmb/L2_success.log"					# lt/lt-archive
#setenv L2_SUCCESS_LOG_PATH "/home/rmb/sprat_l2_pipeline/logs/L2_success.log"			# rmb/laptop

setenv L2_FAIL_LOG_PATH "/home/rmb/devel/SPRAT/sprat_l2_pipeline/logs/L2_fail.log"		# rmb/desktop
#setenv L2_FAIL_LOG_PATH "/home/data/rmb/L2_fail.log"						# lt/lt-archive
#setenv L2_FAIL_LOG_PATH "/home/rmb/sprat_l2_pipeline/logs/L2_fail.log"				# rmb/laptop

setenv LD_LIBRARY_PATH /usr/lib:/usr/lib64:/usr/lib/gsl						# all

setenv L2_EXT_SOFTWARE_PATH_IM "/usr/bin"							# all
setenv L2_EXT_SOFTWARE_PATH_GNUPLOT "/usr/bin"							# all

# DO NOT ALTER PAST THIS LINE
# ----------------------------------------------------------------------------------- #

##########################
# Set up shell variables #
##########################

setenv L2_BIN_DIR $L2_BASE_DIR/bin
setenv L2_LIB_DIR $L2_BASE_DIR/lib
setenv L2_CONFIG_DIR $L2_BASE_DIR/config
setenv L2_SRC_DIR $L2_BASE_DIR/src
setenv L2_SCRIPT_DIR $L2_BASE_DIR/scripts
setenv L2_MAN_DIR $L2_BASE_DIR/man
setenv L2_TEST_DIR $L2_BASE_DIR/test

setenv L2_ERROR_CODES_FILE $L2_CONFIG_DIR/ERROR_CODES

setenv L2_HEADER_FILE $L2_MAN_DIR/HEADER
setenv L2_SPC_BLURB_FILE $L2_MAN_DIR/SPRAT_RED_CLIP
setenv L2_SPF_BLURB_FILE $L2_MAN_DIR/SPRAT_RED_FIND
setenv L2_SPTS_BLURB_FILE $L2_MAN_DIR/SPRAT_RED_TRACE_SDIST
setenv L2_SPCS_BLURB_FILE $L2_MAN_DIR/SPRAT_RED_CORRECT_SDIST
setenv L2_SPA_BLURB_FILE $L2_MAN_DIR/SPRAT_RED_ARCFIT
setenv L2_SPR_BLURB_FILE $L2_MAN_DIR/SPRAT_RED_REBIN
setenv L2_SPE_BLURB_FILE $L2_MAN_DIR/SPRAT_RED_EXTRACT
setenv L2_SPRF_BLURB_FILE $L2_MAN_DIR/SPRAT_RED_REFORMAT

################
# Set up shell #
################

limit stacksize unlimited
source $L2_SCRIPT_DIR/L2_aliases

##############################
# Set permissions on scripts #
##############################

chmod +x $L2_SCRIPT_DIR/*

######################################################################################################
# Create time log file ($L2_TIME_LOG_PATH) and fail log file ($L2_FAIL_LOG_PATH) if it doesn't exist #
######################################################################################################

if (! -e $L2_SUCCESS_LOG_PATH) then

	echo "L2_SUCCESS_LOG\n\nStart Timestamp,Target File,Arc File,Continuum File,Configuration,Execution Time (s),Number of filled HDUs,Warning Message" > $L2_SUCCESS_LOG_PATH

endif

if (! -e $L2_FAIL_LOG_PATH) then 

	echo "L2_FAIL_LOG\n\nStart Timestamp,Target File,Arc File,Continuum File,Error Message" > $L2_FAIL_LOG_PATH

endif

exit(0)

